### ISSUE TITLE
[Discussion] PAL2.0 Feature Set Milestone 1

### ISSUE THREAD

**Issue by utkumaden** [utkumaden/opentk#8]
## Supported Platforms
- [ ] Windows (Win32) (Windows 7/10/11)
- [ ] Linux (X11) (Debian 11, Ubuntu 20.04)

## Supported Window Features
- [ ] Get/Set Window Title
- [ ] Get/Set Window Icon
- [ ] Get/Set Position
- [ ] Get/Set Size
- [ ] Get/Set Client Size

### Supported Window Events
- [ ] Created
- [ ] Loaded
- [ ] Focus Gained
- [ ] Focus Lost
- [ ] Mouse Enter
- [ ] Mouse Leave
- [ ] Size Changed
- [ ] Drag Enter
- [ ] Drag Leave
- [ ] Drag Drop
- [ ] Fullscreen State Changed
- [ ] Window State Change (Hidden, Shown, Minimized, Maximized)
- [ ] Text Events
- [ ] Key Events
- [ ] Mouse Events
