### ISSUE TITLE
[Discussion] PAL2.0 Feature Milestone 2

### ISSUE THREAD

**Issue by utkumaden** [utkumaden/opentk#9]
### Window Events
- [ ] IME Text Input
- [ ] Joystick
- [ ] Multi-threading Multi-Window

## Multi Monitor
- [ ] Display Mode Listing
- [ ] 

## UWP CoreWindow Support?
Technically another platform for Windows. Worth supporting?

## Discuss a Concept of "Surface"
What makes a surface a "surface"?
